name: Deploy to Firebase
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Install dependensi frontend
      - run: npm ci
        working-directory: ./client
      - run: npm run build
        working-directory: ./client
      # Install dependensi functions
      - run: npm ci
        working-directory: ./server
      # Deploy Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: wartelsuspas-app
      # Deploy Functions
      - name: Install Firebase Tools and Deploy Functions
        run: |
          npm install -g firebase-tools
          echo "Firebase CLI version: $(firebase --version)"
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ./service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json
          firebase deploy --only functions --project wartelsuspas-full --debug --non-interactive
        working-directory: ./server